version: '3'

services:
  mariadb:
    image: mariadb:ilkridah
    env_file: .env
    build:
      context: ./requirements/mariadb
      args:
        D_B: ${D_B}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  nginx:
    image: nginx:ilkridah
    build: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_started

  wordpress:
    image: wordpress:ilkridah
    env_file: .env
    build: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_started

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /Users/ilkridah/Desktop/Inception/data/mariadb
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /Users/ilkridah/Desktop/Inception/data/wordpress
      o: bind
